name: Docker Build and Push

on:
  push:
    branches: ["main", "master"]  # Trigger on push to main/master branch

env:
  REGISTRY: docker.io  # Default to Docker Hub (or use another registry like GHCR)
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/kriya-bot  # Replace with your image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}  # Tag with Git commit SHA